### ISSUE TITLE
Failed to use model trained with i-vectors when computing ppg

### ISSUE THREAD

**Issue by a2d8a4v** [guanlongzhao/fac-via-ppg#16]
Hi, I encounter a problem when using the `compute_full_ppg` function at `src/ppg/compute_ppg.py` 
I used librispeech to train an acoustic model with i-vectors, and I write my code like these below:

`def feats_scp_reader(path,name):`
   `p = path+"/"+name+".scp"`
   `rtn = {}`
   `with ReadHelper('scp:{}'.format(p)) as reader:`
      `for key, numpy_array in reader:`
         `rtn[key] = numpy_array`
      `return rtn`
`...`
`feats=feats_scp_reader(base+"/data/test","feats")`
`...`
`for i,(j,k) in enumerate(feats.items()):
   print(j)
   nnet = decode.read_nnet3_model(base+"/path/to/own/model/final.raw")
   ppg = compute_full_ppg(nnet,Matrix( k )).numpy()
   ...`

and the code went wrong with this line:
`   ppg = compute_full_ppg(nnet,Matrix( k )).numpy()`

the error message is just like below
`LOG ([5.5.195~1-9daa6]:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 5 orphan nodes.`
`LOG ([5.5.195~1-9daa6]:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 11 orphan components.`
`LOG ([5.5.195~1-9daa6]:Collapse():nnet-utils.cc:1378) Added 6 components, removed 11`
`ERROR ([5.5.195~1-9daa6]:EnsureFrameIsComputed():nnet-am-decodable-simple.cc:105) Neural net expects 'ivector' features with dimension 100 but you provided 0`
`ERROR ([5.5.195~1-9daa6]:EnsureFrameIsComputed():nnet-am-decodable-simple.cc:105) Neural net expects 'ivector' features with dimension 100 but you provided 0`
`Traceback (most recent call last):`
  `File "kaldi_load_feats.py", line 56, in <module>`
`    ppg = compute_full_ppg(nnet,Matrix( k )).numpy()`
`  File "xxx/fac-via-ppg/src/ppg/compute_ppg.py", line 68, in compute_full_ppg`
`    nnet_computer.get_output_for_frame(i, temp)`
`RuntimeError: C++ exception: `

Is it possible to use models trained with i-vectors with the `compute_ppg` function? or any other way to solve this kind of problem.

peace

**Comment by guanlongzhao** [comment]
So this repo does not support using AMs trained with i-vectors, although it is possible to do that (I've implemented it before but cannot share the code due to IP reasons, sorry).

On a very high level, you need to write some functions to extract i-vectors (take a look at https://pykaldi.github.io/api/kaldi.ivector.html) and pass both the i-vector and MFCCs (or other filter bank feature of your choice) to the AM. Take a look at https://pykaldi.github.io/api/kaldi.nnet3.html to see how to load the AM and perform inference.

Another possible implementation is to use something like https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/nnet3/chain/get_phone_post.sh to generate PPGs in kaldi, that way I think i-vector-based AMs should work right out of the box. Then you can read the kaldi-generated PPG outputs with something like https://github.com/nttcslab-sp/kaldiio.

I hope this helps.

**Comment by guanlongzhao** [comment]
It really depends on the type of AM because Kaldi has a few different nnet versions (I think there are three), although the most recent Kaldi recipes should be able to train nnet3 models. You can read different nnets with their corresponding pykaldi libraries. After that, you would need to generate input features that suit your specific AM type.

In general, I feel that it would be much easier to use native Kaldi binaries (e.g., tools in https://github.com/kaldi-asr/kaldi/blob/master/egs/wsj/s5/steps/nnet3/chain/get_phone_post.sh) to get the PPGs instead of writing your own python wrapper.
